# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='accounts.MyUser'),
        ),
    ]
