# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import tmsapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmsapp', '0005_auto_20180530_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='activity_number',
            field=models.ForeignKey(default=0, on_delete=tmsapp.models.Task, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=tmsapp.models.Task, related_name='task_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
    ]
