# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0008_auto_20180530_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='start_date',
            new_name='task_name1',
        ),
    ]
