# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import tmsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0009_auto_20180530_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='task_name1',
            field=models.ForeignKey(blank=True, null=True, on_delete=tmsapp.models.Task, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=120),
        ),
    ]
