# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0011_auto_20180530_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=120, verbose_name='accounts.MyUser'),
        ),
    ]
