# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0012_auto_20180530_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=120),
        ),
    ]
