# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0013_auto_20180530_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='task_name1',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=120, verbose_name='Task name'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
