# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0015_auto_20180530_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='duration',
            field=models.TimeField(verbose_name='Duration'),
        ),
    ]
